Desmos, excluding export functionality. (#164)
* Check for lti_sourcedid in startassess

(cherry picked from commit 09037bc691e180d28ad9f4e7d7c47a5c596ee131)

* PROD-643 add Desmos Interactive Item, view and modify, but not rearange

* update icons

* move course item files out of OHM. more demos item interaction

* added main layout for course items

* use  and

* Make the gear icon actions work while efactoring and adding comments

* update to find for db calls and direct reference properties

* remove unnecessary javascript

* use imas_libraries to tag desmos_interactives.libs for learning objectives

* add tracking object. Track student views. Track teacher add, edit, copy

* add desmos to dropdown

* added lux.css file to itemadd.php

* Add basic Lux for classes, HTML cleanup

* prod-679 authoring desmos steps

* fixing table creation

* added form inputs with new calendar icon

* refactor input with icon AGAIN

* move css from page to lumen.css

* PROD-807 exporting and importing imathas and canvas cartridges

* PROD-676 store json in figure element data to make copy and edit between steps function independently

* Add comments for OHM-specific code

* export as assignment in assn folder

* PROD-807 blti export link

* add lux-temp.css

* delete unneeded iicon

* PROD-746 LTI integration. Use imas_items.id to pull item detail

* change use of DesmosInteractive to DesmosItem

* PROD-746 ltiitemtype 38 for desmos

* PROD-746 update debug to use numbers in 30s for new items

* PROD-746 looking for item placement

* PROD-746 redirect to itemview page

* PROD-746 adding ohm-specific comments

* PROD-746 issues with student view

* PROD-746 add comments. update imas_lti_placements.placementtype to use same as imas_items.itemtype.

* PROD-746 fix placementtype

* PROD-746 fix placementtype

* PROD-746 fix courseid

* PROD-746 add redirect to itemview

* PROD-746 add redirect to itemview

* update temp css

* removed redundant lumen.css link from itemadd.php

* fix merge conflicts

* moved css from lumen.css to temp file

* moved lux overriding styles out of lumen.css to temp stylesheet

* change display_name to itemname
add itemtype to link to imas_items.itemtype
fixes export desmos icon

* first refactor html

* added temp delete buttons

* rearrange temp css doc and basic stying for view page

* OHM-118 grade book category for items

* OHM-118 non-canvas lti param

* OHM-118 lti placement of DesmosItem

* OHM-118 fix non-canvas lti param

* OHM-118 update placement typeid

* OHM-118 small changes to linking

* html/css complete

* fixed desmos logo

* findCourseItem when setplacement

* OHM-118 add export for black board

* OHM-134 link to desmos CDN for desmos item

* fixed step overflow

* deleted unnecessary line

* all changes made, omitting js and js related markup changes

* only add step on load if no other steps exist. make delete x button remove step

* OHM-121 preview edit desmos before save

* make added steps work with showSteps()

* OHM-121 preview

* OHM-138 only admin can add desmos item

* OHM-121 preview disable and re-enable lux until components are used

* OHM-109 desmos plugin basics

* remove 'Delete' button for steps

* Show/hide TinyMCE for each Desmos step in edit mode.

* OHM-109 attempting to get TinyMCE to use Desmos class

* do not need to hide textarea

* removed $useeditor near the top

* update for views to continue to work with showSteps()

* Load the Desmos calculator script and parse JSON as a TinyMCE plugin.

* Removed unnecessary init function.

* update for showing steps and tinymce editor full hight

* OHM-109 edit desmos in popup

* making preview work and starting to get &quot; to work with desmos and tinymce

* add popup html

* Consolidate styles

* Fixing merge

Added missing files from ohm-110 and got JS working again

* Reworking delete buttons

* More robust delete function

Added show this function

* Update class name

* Add utility styles to lux-temp

* Add drag icon to desmos svg symbols

* Update markup for drag and drop

Update addStep function with the same markup

* Add drag and drop JS

* Add class name to delete button

Use show-this function to elim dupe code

* Clean up and reorg CSS

Start adding drag and drop styles

* update and simplify styles

* Update classnames

* Rewrite show function

Comment out the student nav JS

* Add necessary DnD attributes to newly added rows

* Fixes post rebase

* After drag, make current object selected

* Desmos administration supporting hidden folders

* OHM-138 must be lumen user to add desmos interactive

* use config for desmos calendar file. Should link to CDN but may use local file if working offine

* Merge drag and drop with preview. Still need to fix
1. Drag and drop does not work but keyboard moving does
2. Title and text relationship is not kept on move
3. Delete does not delete text only title
4. Need to save the new order in the database
5. Add button adds title but does not add text area
6. New textarea should use tinymce

* Corrected title and text relationship. New textarea uses tinymce

* view use data-num as well to tie together title text relationship

* Desmos TinyMCE plugin only show on Desmos Interactive page

* Update image and text for TinyMCE plugin

* update new desmos plugin image

* OHM-121: UI changes as requested.

- Moved "Preview" button to the bottom of the page, next to "Save".
- Removed "Save and Exit" button from the preview page.
- Added a change warning at the top of the preview page.

* Use desmos_items.steporder to save and display the steps in the correct order

* Remove duplicate css

* Remove extraneous curly bracket

* Clean up, reorder CSS

* Allow Full Admin to Add Desmos

* Updated the Desmos preview warning icon with an SVG.

OHM-121

* Replaced Desmos icon with a non-transparent one.

OHM-121

* Updated Desmos edit/preview styling as requested.

OHM-121

* Override entire page's background color on Desmos preview.

OHM-121

* Remove unnecessary hash from parent name

* make drag work for new items. Use numsteps for all steps including old steps

* Restyled buttons, fixed spacing issues, step-widths, tiny mce border

* fixed spacing

* OHM-174 styles for desmos modal

* OHM-174 preview click to edit

* OHM-136 import existing calculator from desmos.com

* OHM-136 change style

* remove alert

* reorder css rules

* reorder css rules again

* Bugfix: You can't move Desmos items that are in blocks (#160)

OHM-194

* Bugfix: "Add An Item" dropdown in block is not removed (#161)

OHM-195 - If a Desmos item is added to a block and then all items
in a block are deleted, the second "Add An Item" dropdown at the
end of the block is not removed

* Bugfix: You can't move Desmos items that are in blocks (#160) (#162)

This commit completes the previous fix in commit ID
ac76e90b9b4dd10771cb427471d91debbc2df984.

OHM-194

* Bugfix: Handle uncaught PDOException for Desmos items via LMS.

Quick fix to catch the exception and display a user-friendly message
instead.

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'courseid' cannot be null in /var/app/current/bltilaunch.php:2574 Stack trace: #0 /var/app/current/bltilaunch.php(2574): PDOStatement->execute(Array) #1 {main} thrown in /var/app/current/bltilaunch.php on line 2574

* Added an EB extension to install Xdebug in staging environment.

For this to work, the environment variable "XDEBUG_ENABLED" must
be set to "true".

* Undo Desmos related changes to admin/ccexport.php.

This reverts commits:
  ce400425ba22b0abce16ce2a122c70fcebe1f408
  7c1f99d533baef05f4ece47813869f67c1f81a44
  78121460ec9a813fb2a4042b26b753a27f584777

* Removed Desmos features from bltilaunch.php.

* Removed Desmos features from admin/ccexport-generate.php.

* Removed Desmos features from admin/bbexport-generate.php.

* Removed Desmos features from admin/exportitems2.php.

Co-authored-by: David Lippman <drlippman@yahoo.com>
Co-authored-by: Alena Holligan <alena@holligan.us>
Co-authored-by: Treasure Porth <treasure.rose@gmail.com>
Co-authored-by: Angelique <hello@angeliqueweger.com>