Fixed: Incorrect namespacing.
OHM-34: OHM Production & Staging | Group Settings page should
display the payment options

For some groups, instead of seeing the payment option pulldown,
we are getting the error:

Fatal error: Class 'OHM\StudentPayApiResult' not found in
/var/app/current/admin/forms.php on line 1412